### PR TITLE
Update french strings.xml

### PR DESCRIPTION
**Pull request by Ilithy**

### CODE REVIEW

**Comment by cliuff** [comment]
I suggest additional changes to be made:
- The strings.xml for French in France `values-fr-rFR/strings.xml` should also be changed, both files were the same, just replace it with the new content.
- Can you localize "override force-dark" according to the screenshot
InkedScreenshot_1642040134_LI

**Comment by Ilithy** [comment]
Hello, no problem, I'll take care of it

**Comment by Ilithy** [comment]
Done, I also modified as requested the part dedicated to the force-dark option in Smart Dark, I let you check all this, thanks a lot.

**Comment by cliuff** [comment]
Thanks it's very nice, however I noticed some modifications are not present in the France variant file, please make sure the two files have the same content unless it's for regional dialect differences.

**Comment by cliuff** [comment]
I suggest you copy all content in `values-fr/strings.xml` and paste to replace the content in `values-fr-rFR/strings.xml`

**Comment by cliuff** [comment]
image

**Pull request merged**
